# Generated by Django 4.1.5 on 2023-01-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gen', '0003_rename_image_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='size',
            new_name='resolution',
        ),
    ]
