# Generated by Django 4.1.5 on 2023-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_chatmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='alt_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
