# Generated by Django 4.1.5 on 2023-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chatmodel_alt_info_alter_chatmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='last_usage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
