# Generated by Django 4.1.5 on 2023-01-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='answer',
            new_name='response',
        ),
    ]
