# Generated by Django 4.1.5 on 2023-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settings',
            table='settings',
        ),
    ]
