# Generated by Django 4.1.5 on 2023-01-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_settings_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='user_id',
            new_name='user',
        ),
    ]
